name: Release Workflow
run-name: Release Workflow

on:
  push:

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      # - name: Create Release Tag
      #   id: create_tag
      #   run: |
      #     TAG_NAME="v$(date +'%Y%m%d%H%M%S')"
      #     git tag $TAG_NAME
      #     git push origin $TAG_NAME

      - name: Create GitHub Release
        run: |
          TAG_NAME=$(git describe --tags $(git rev-list --tags --max-count=1))
          gh release create $TAG_NAME --title "Release $TAG_NAME" --notes "Release created by GitHub Actions."